package com.rule
import FrameworkSwing.tactiqueProperties

rule "tactique 1"
	when 
		tactiquePropertiesObject: tactiqueProperties(Bindingtime=="Compile-time", granularity=="Medium", evolution=="Open")
	then
		tactiquePropertiesObject.addElement("Aspect programming");
	end
rule "tactique 2"
	when 
		tactiquePropertiesObject: tactiqueProperties(Bindingtime=="Compile-time", granularity=="Coarse", evolution=="Open")
	then
		tactiquePropertiesObject.addElement("Aspect programming");
	end
rule "tactique 3"
	when 
		tactiquePropertiesObject: tactiqueProperties(Bindingtime=="Compile-time", granularity=="Any", evolution=="Close")
	then
		tactiquePropertiesObject.addElement("Conditional-Compilation");
		tactiquePropertiesObject.addElement("Clone-and-own");
		
	end
rule "tactique 4"
	when 
		tactiquePropertiesObject: tactiqueProperties(Bindingtime=="Compile-time", granularity=="Any", evolution=="Open")
	then
		tactiquePropertiesObject.addElement("Dependency injection");
	end

rule "tactique 5"
	when 
		tactiquePropertiesObject: tactiqueProperties(Bindingtime=="Run-time", granularity=="Fine", evolution=="Close")
	then
		tactiquePropertiesObject.addElement("Conditional-Execution");
	end
rule "tactique 6"
	when 
		tactiquePropertiesObject: tactiqueProperties(Bindingtime=="install-time")
	then
		tactiquePropertiesObject.addElement("install");
	end